### ISSUE TITLE
Probleme mit tags

### ISSUE THREAD

**Issue by dive13** [hschottm/literature#1]
Es gibt schon seit längerer Zeit Probleme bei der Verwendung von [literature] gemeinsam mit [tags], d.h. die Filterung der Literaturliste durch die Auswahl von tags klappt überhaupt nicht mehr. Verwendete Versionen: literature 3.1.0, tags 3.4.2, Contao 3.5.24
Siehe auch https://community.contao.org/de/showthread.php?50245-literature-Literaturverwaltung-mit-Auszeichnungen-Tags-Filtern&highlight=literature
Wäre sehr toll, wenn das gefixt werden könnte!

**Comment by hschottm** [comment]
Fixed in 134658c821201f8399f1e2a746e740f7263815c8
